apiVersion: v1
kind: Pod
metadata:
  name: basic-pod
  labels:
    app.kubernetes.io/name: basic
spec:
  containers:
    - name: basic-container
      image: busybox
      command: ["sh", "-c", "echo Hello Kubernetes! && sleep 3600"]
