apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: flagger-loadtester
  namespace: apps
spec:
  interval: 6h
  url: oci://ghcr.io/fluxcd/flagger-manifests
  ref:
    semver: 1.x
  verify:
    provider: cosign
