apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: istio-charts
  namespace: flux-system
spec:
  url: https://istio-release.storage.googleapis.com/charts
  interval: 1h
---
# installs CRDs, namespaces, and RBAC
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: base
      sourceRef:
        kind: HelmRepository
        name: istio-charts
  targetNamespace: istio-system
  install:
    createNamespace: true
---
# installs the Istio control plane
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
spec:
  interval: 1h
  dependsOn:
    - name: istio-base
  chart:
    spec:
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio-charts
  targetNamespace: istio-system
---
# installs the ingress gateway
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-gateway
  namespace: flux-system
spec:
  interval: 1h
  dependsOn:
    - name: istiod
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio-charts
  targetNamespace: istio-system
