apiVersion: v1
kind: Service
metadata:
  name: random-site
spec:
  selector:
    app: static-site
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
