apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-site-4
  labels:
    app: static-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-site
      site: site-4
  template:
    metadata:
      labels:
        app: static-site
        site: site-4
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: index
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: my.conf
      volumes:
        - name: index
          configMap:
            name: page-content-4
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: page-content-4
  labels:
    app: myapplication
data:
  index.html: |
    <html>
    <head>
      <title>My custom site</title>
    </head>
    <body>
      <h1>This is site 4</h1>
    </body>
    </html>
