apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
  labels:
    app: {{ $.Chart.Name }}
spec:
  selector:
    app: {{ $.Chart.Name }}-deployment
  ports:
    - name: http
      protocol: TCP
      port: {{ $.Values.externalPort }}
      targetPort: {{ $.Values.internalPort }}
  type: LoadBalancer
