apiVersion: v1
kind: Service
metadata:
  name: todo
spec:
  selector:
    app: todo
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: other
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
